
GRAMMAR_A2 = [
(1,"Presente indicativo","Fondamenta","verbi regolari; essere, avere; verbi frequenti"),
(2,"Articoli determinativi","Fondamenta","il, lo, la, l’, i, gli, le"),
(3,"Articoli indeterminativi","Fondamenta","un, uno, una, un’"),
(4,"Nomi e aggettivi: genere e numero","Fondamenta","accordo maschile/femminile, singolare/plurale"),
(5,"C’è / Ci sono","Fondamenta","descrivere presenza e luoghi"),
(6,"Preposizioni semplici","Preposizioni","di, a, da, in, con, su, per, tra/fra"),
(7,"Preposizioni articolate","Preposizioni","del, al, dal, nel, sul..."),
(8,"Possessivi","Determinanti","mio, tuo, suo, nostro, vostro, loro; famiglia"),
(9,"Dimostrativi","Determinanti","questo, quello"),
(10,"Pronomi diretti","Pronomi","mi, ti, lo, la, ci, vi, li, le"),
(11,"Pronomi indiretti","Pronomi","mi, ti, gli, le, ci, vi"),
(12,"Pronomi combinati: introduzione","Pronomi","me lo, te la, glielo..."),
(13,"Passato prossimo con avere","Passato","avere + participio passato"),
(14,"Passato prossimo con essere","Passato","essere + participio e accordo"),
(15,"Participi passati irregolari","Passato","fatto, detto, visto, preso, scritto..."),
(16,"Imperfetto","Passato","abitudini, descrizioni, azioni in corso"),
(17,"Passato prossimo vs imperfetto","Passato","evento concluso vs sfondo/abitudine"),
(18,"Verbi riflessivi","Verbi","alzarsi, vestirsi, sentirsi..."),
(19,"Dovere, potere, volere","Verbi","modali nel presente e passato"),
(20,"Futuro semplice","Futuro","forme regolari e irregolari frequenti"),
(21,"Imperativo informale","Comunicazione","tu, noi, voi; negativo"),
(22,"Comparativi","Descrivere","più/meno... di/che; come/quanto"),
(23,"Superlativi","Descrivere","il più; -issimo"),
(24,"Ci","Particelle","luogo e usi frequenti A2"),
(25,"Ne","Particelle","quantità e provenienza A2"),
(26,"Stare + gerundio","Aspetto","azione in corso"),
(27,"Condizionale presente: cortesia","Comunicazione","vorrei, potrei, dovrebbe..."),
(28,"Pronomi relativi: che e cui","Frase","collegare frasi semplici"),
(29,"Connettivi A2","Frase","perché, quindi, però, mentre, anche se"),
(30,"Avverbi e quantità","Frase","molto, poco, abbastanza, troppo, già, ancora"),
(31,"Si impersonale: introduzione","Frase","usi quotidiani semplici"),
(32,"Ripasso finale A2","Revisione","integrazione completa delle strutture A2"),
]
GRAMMAR_A2=[{"unit":u,"title":t,"group":g,"focus":f} for u,t,g,f in GRAMMAR_A2]

WRITING_TOPICS = [
"Presentati e descrivi la tua vita attuale.",
"Descrivi la tua routine durante una giornata normale.",
"Descrivi la tua camera o casa ideale.",
"Racconta cosa hai fatto lo scorso fine settimana.",
"Scrivi un messaggio per invitare un amico a cena.",
"Descrivi una persona importante per te.",
"Racconta una vacanza o un viaggio.",
"Descrivi la città in cui vivi.",
"Parla dei tuoi studi e dei tuoi obiettivi.",
"Descrivi il tuo rapporto con sport e salute.",
"Racconta un problema che hai risolto.",
"Scrivi una breve email per chiedere informazioni.",
"Confronta due città o due posti.",
"Racconta un ricordo della tua infanzia.",
"Descrivi un lavoro che ti piacerebbe fare.",
"Esprimi una semplice opinione sulla tecnologia.",
"Parla dei vantaggi e svantaggi dei social media.",
"Descrivi un film, libro o serie che ti è piaciuto.",
"Parla di un'abitudine che vuoi cambiare.",
"Scrivi dei tuoi progetti per il futuro.",
]

CONVERSATION_TOPICS=[
"Presentarsi","Routine quotidiana","Bar e ristorante","Fare la spesa","Casa","Università",
"Lavoro","Viaggi","Salute e farmacia","Sport","Amicizia","Tecnologia","Trasporti",
"Vivere in Italia","Cinema","Musica","Cibo","Shopping","Progetti futuri","Una notizia semplice"
]
